name: C/C++ CI

on: [push, pull_request]

jobs:
  nx-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: checkout
      run: |
        #wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-get add-key -
        #sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        #sudo apt-get add-repository ppa:cginternals/ppa
        sudo apt-get update
        sudo apt-get install -y cmake ccache vulkan-sdk python3-setuptools mesa-common-dev libglu1-mesa-dev ninja-build libcurl4-openssl-dev libsdl2-dev libssl-dev zlib1g-dev libuv1-dev libc-ares-dev libavcodec-dev libavfilter-dev libavutil-dev libswscale-dev gcc g++ build-essential
        pip3 install wheel
        pip3 install aqtinstall
        pyhton3 -m aqtinstall 
        curl -sSfLO https://github.com/NixOS/patchelf/releases/download/0.12/patchelf-0.12.tar.bz2
        tar xvf patchelf-0.12.tar.bz2
        cd patchelf-0.12/
         ./configure
        make && sudo make install
        cd ../
        git clone --recursive https://github.com/wtfloltk/decaf-emu
        cd decaf-emu
        cmake -S . -B out -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake
        cd out
        make
